VULN_PORTS = {
    21:   ("FTP non sécurisé", "high"),
    22:   ("SSH obsolète ou faible", "medium"),
    23:   ("Telnet non sécurisé", "critical"),
    25:   ("SMTP ouvert (risque de spam relay)", "high"),
    53:   ("DNS ouvert (risque d'amplification DDoS)", "high"),
    69:   ("TFTP sans authentification", "high"),
    80:   ("HTTP non chiffré", "medium"),
    111:  ("Portmapper exposé (NFS)", "high"),
    123:  ("NTP ouvert (amplification DDoS)", "high"),
    137:  ("NetBIOS exposé", "medium"),
    139:  ("SMBv1 actif", "critical"),
    161:  ("SNMP v1/v2c (communauté en clair)", "high"),
    389:  ("LDAP non chiffré", "high"),
    445:  ("SMB vulnérable (EternalBlue)", "critical"),
    512:  ("Rexec exposé", "high"),
    513:  ("Rlogin exposé", "high"),
    514:  ("Rsh exposé", "high"),
    873:  ("Rsync ouvert sans auth", "high"),
    1025: ("RPC high ports exposés", "medium"),
    1433: ("MSSQL exposé", "high"),
    1521: ("Oracle DB exposée", "high"),
    2049: ("NFS ouvert", "high"),
    2375: ("Docker API sans auth", "critical"),
    27017: ("MongoDB sans authentification", "critical"),
    3306: ("MySQL exposé", "high"),
    3389: ("RDP exposé", "high"),
    5432: ("PostgreSQL exposé", "high"),
    5900: ("VNC sans mot de passe", "critical"),
    6379: ("Redis sans authentification", "critical"),
    8000: ("Serveur web de dev exposé", "medium"),
    8080: ("Proxy/HTTP alternatif non sécurisé", "medium"),
    9200: ("Elasticsearch sans auth", "critical"),
}


VULN_SERVICES = {
    "ftp":        ("FTP non sécurisé", "high"),
    "telnet":     ("Telnet obsolète", "critical"),
    "http":       ("HTTP non chiffré", "medium"),
    "smtp":       ("SMTP ouvert (risque de relay)", "high"),
    "dns":        ("DNS ouvert (amplification DDoS)", "high"),
    "mysql":      ("MySQL accessible", "high"),
    "postgres":   ("PostgreSQL accessible", "high"),
    "redis":      ("Redis sans auth", "critical"),
    "ldap":       ("LDAP non chiffré", "high"),
    "smb":        ("SMB vulnérable", "critical"),
    "nfs":        ("NFS exposé", "high"),
    "docker":     ("Docker API sans authentification", "critical"),
    "mongodb":    ("MongoDB sans authentification", "critical"),
    "vnc":        ("VNC sans mot de passe", "critical"),
    "mqtt":       ("MQTT sans TLS", "medium"),
    "elasticsearch": ("Elasticsearch sans auth", "critical"),
    "kibana":     ("Kibana accessible sans auth", "high"),
    "snmp":       ("SNMP v1/v2c (communauté en clair)", "high"),
}


VULN_VERSIONS = [
    ("OpenSSH", "<", "7.4", "OpenSSH obsolète", "medium"),
    ("Apache", "<", "2.4.50", "Apache vulnérable (path traversal)", "high"),
    ("nginx", "<", "1.18.0", "nginx obsolète", "medium"),
    ("MySQL", "<", "5.7", "MySQL obsolète", "high"),
    ("PHP", "<", "7.4", "PHP obsolète (fin de support)", "high"),
    ("OpenSSL", "<", "1.1.1", "OpenSSL vulnérable (Heartbleed/anciennes CVE)", "critical"),
    ("Samba", "<", "4.7", "Samba vulnérable (CVE anciennes)", "high"),
    ("Redis", "<", "5.0", "Redis obsolète", "medium"),
    ("PostgreSQL", "<", "12", "PostgreSQL obsolète", "medium"),
    ("Node.js", "<", "14", "Node.js obsolète", "medium"),
    ("Python", "<", "3.8", "Python obsolète", "low"),
]

